trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  # - group: 'DatabricksSettings'
  - name: SOURCE_DIR
    value: q_a/azure_devops


steps:
# 1. Install Databricks CLI (if not present)
- script: |
    if ! command -v databricks &> /dev/null; then
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        echo "Databricks CLI installed";
    fi
  displayName: Databricks CLI install


- script: |
    export DATABRICKS_AZURE_RESOURCE_ID=/subscriptions/bf9e1a1a-dfec-417c-afa4-fd2fe4aaf814/resourceGroups/AzureDataBricks/providers/Microsoft.Databricks/workspaces/unity
    export ARM_CLIENT_ID=7612badb-4916-4534-888e-9c338d6e92be
    export ARM_USE_MSI=true
    export DATABRICKS_HOST=https://adb-2248610192980166.6.azuredatabricks.net
    databricks bundle validate

# # 2. Run DAB validation
# - script: |
#     databricks bundle validate
#   workingDirectory: $(SOURCE_DIR)
#   displayName: DAB validation
#   # env:
#   #   DATABRICKS_HOST: $(DATABRICKS_HOST)
#   #   DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)


# - script: |
#     databricks bundle deploy
#   workingDirectory: $(SOURCE_DIR)
#   displayName: DAB deployment
#   # env:
#   #   DATABRICKS_HOST: $(DATABRICKS_HOST)
#   #   DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
