trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'DatabricksSettings'

steps:
# 1. Install Databricks CLI (if not present)
- script: |
    if ! command -v databricks &> /dev/null; then
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        echo "Databricks CLI installed";
    fi


# 2. Run DAB validation
- script: |
    pwd
    ls -la
    databricks bundle validate
  env:
    DATABRICKS_HOST: $(DATABRICKS_HOST)
    DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

