trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: 'DatabricksSettings'
  - name: SOURCE_DIR
    value: q_a/azure_devops_sp


steps:
# 1. Install Databricks CLI (if not present)
- script: |
    if ! command -v databricks &> /dev/null; then
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        echo "Databricks CLI installed";
    fi


# 2. Run DAB validation
- script: |
    databricks bundle validate
  workingDirectory: $(SOURCE_DIR)
  # env:
  #   DATABRICKS_HOST: $(DATABRICKS_HOST)
  #   DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

- script: |
    databricks bundle deploy
  workingDirectory: $(SOURCE_DIR)
  # env:
  #   DATABRICKS_HOST: $(DATABRICKS_HOST)
  #   DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
